pessoa = str(input('Qual é o seu nome? '))
print('\033[0;31mAlgumas informações de onde você mora... ')
rua = str(input('Qual é o nome da rua onde você mora? ')).strip()
print('\033[0;31mO nome da rua onde você mora é {}'. format(rua.title ()))
print('\033[0;31mO nome da rua onde você mora tem {} letras'.format(len(rua)-rua.count(' ')))
print('\033[0;31mO nome da rua onde você mora tem {} letras e'.format(rua.count('e')))
bairro = str(input('Qual é o nome do bairro onde você mora? '))
print('\033[0;35mO nome do bairro onde você mora é {}'.format(bairro.title ()))
print('\033[0;35mO números de letras que o nome do seu bairro tem é {}'.format(len(bairro)-bairro.count(' ')))
print('\033[0;35mO nome da rua onde você mora tem {} letras o'.format(bairro.count('o')))
cep = str(input('Qual é o CEP de onde você mora? '))
print('\033[0;33mO número do CEP onde você mora é {}'.format(cep))
print('\033[0;33mO número do CEP onde você mora possui {} números'.format(len(cep)))
print('\033[0;33mO número do CEP onde você mora possui {} números 3'.format(cep.count ('3')))
cidade = str(input('Qual o nome da cidade onde você mora?' ))
print('\033[0;36mO nome da cidade onde você mora é {}'.format(cidade.upper()[:30]))
print('\033[0;36mO nome dessa pessoa é {}, ela mora na rua {}, no bairro {} com o CEP {} situado na cidade de {}'.format(pessoa,rua, bairro, cep, cidade.upper()[:30]))

